import React,{useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
type Ex={name:string;sets:number;weight:number;min:number;max:number};type W={name:string;ex:Ex[]};type P={name:string;workouts:W[]};
const load=():P|null=>{try{return JSON.parse(localStorage.getItem('program')||'null')}catch{return null}};
function App(){const[p,setP]=useState<P|null>(load);const[active,setActive]=useState(0);const[session,setSession]=useState(false);const save=(x:P)=>{setP(x);localStorage.setItem('program',JSON.stringify(x))};
if(!p)return <Setup onSave={save}/>;const w=p.workouts[active%p.workouts.length];return <main><header><small>АКТИВНАЯ ПРОГРАММА</small><h1>{p.name}</h1></header>{session?<Session w={w} done={()=>{setSession(false);setActive(x=>(x+1)%p.workouts.length)}}/>:<><section className="hero"><small>СЛЕДУЮЩАЯ ТРЕНИРОВКА</small><h2>{w.name}</h2><p>{w.ex.length} упражнений · {w.ex.reduce((a,e)=>a+e.sets,0)} подходов</p><button onClick={()=>setSession(true)}>Начать тренировку</button></section><Program p={p} save={save}/></>}</main>}
function Setup({onSave}:{onSave:(p:P)=>void}){const[name,setName]=useState('');const[ws,setWs]=useState<W[]>([]);return <main><h1>Создайте программу</h1><p className="muted">Сначала составьте план тренировок.</p><input placeholder="Название программы" value={name} onChange={e=>setName(e.target.value)}/>{ws.map((w,i)=><WorkoutEdit key={i} w={w} change={x=>{const a=[...ws];a[i]=x;setWs(a)}}/>)}<button className="secondary" onClick={()=>setWs([...ws,{name:'Новая тренировка',ex:[]}])}>+ Добавить тренировку</button><button disabled={!name||!ws.length||!ws.some(w=>w.ex.length)} onClick={()=>onSave({name,workouts:ws})}>Начать программу</button></main>}
function WorkoutEdit({w,change}:{w:W;change:(w:W)=>void}){return <section><input value={w.name} onChange={e=>change({...w,name:e.target.value})}/>{w.ex.map((x,i)=><div className="exercise" key={i}><b>{x.name}</b><span>{x.sets} × {x.min}–{x.max} · {x.weight} кг</span></div>)}<button className="secondary" onClick={()=>{const n=prompt('Название упражнения');if(!n)return;const sets=Number(prompt('Количество подходов','3'))||3;const weight=Number(prompt('Целевой вес, кг','20'))||0;const min=Number(prompt('Повторения от','8'))||8;const max=Number(prompt('Повторения до','12'))||12;change({...w,ex:[...w.ex,{name:n,sets,weight,min,max}]})}}>+ Упражнение</button></section>}
function Program({p,save}:{p:P;save:(p:P)=>void}){return <><h3>Программа</h3>{p.workouts.map((w,i)=><section key={i}><h2>{w.name}</h2>{w.ex.map((e,j)=><div className="exercise" key={j}><b>{e.name}</b><span>{e.sets} × {e.min}–{e.max} · {e.weight} кг</span></div>)}</section>)}<button className="danger" onClick={()=>{if(confirm('Удалить программу и создать новую?')){localStorage.removeItem('program');location.reload()}}}>Создать другую программу</button></>}
function Session({w,done}:{w:W;done:()=>void}){const[data,setData]=useState(w.ex.map(e=>Array.from({length:e.sets},()=>({weight:e.weight,reps:e.min,rir:2,ok:false}))));return <><h2>{w.name}</h2>{w.ex.map((e,i)=><section key={i}><h3>{e.name}</h3><p className="muted">План: {e.sets} × {e.min}–{e.max} · {e.weight} кг</p><div className="labels"><span>№</span><span>кг</span><span>повт.</span><span>RIR</span><span></span></div>{data[i].map((s,j)=><div className="set" key={j}><span>{j+1}</span>{(['weight','reps','rir'] as const).map(k=><input key={k} type="number" value={s[k]} onChange={ev=>{const d=data.map(a=>a.map(x=>({...x})));d[i][j][k]=Number(ev.target.value);setData(d)}}/>)}<button className={s.ok?'check ok':'check'} onClick={()=>{const d=data.map(a=>a.map(x=>({...x})));d[i][j].ok=!d[i][j].ok;setData(d)}}>{s.ok?'✓':'○'}</button></div>)}</section>)}<button onClick={()=>{const hist=JSON.parse(localStorage.getItem('history')||'[]');hist.unshift({date:new Date().toISOString(),name:w.name,data});localStorage.setItem('history',JSON.stringify(hist));done()}}>Завершить тренировку</button></>}
createRoot(document.getElementById('root')!).render(<App/>);
